---
title: "Initial data exploration"
author: "Abby Lewis"
date: "2024-08-21"
output: html_document
---

Load data and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)

ch4 <- read_csv("Raw_data/GENX_Flux_SD_Loggernet_2021-05-05_to_2022-12-31_derived.csv", show_col_types = FALSE) %>%
  mutate(Temp = sub("e", "", zone_treatment),
         Temp = ifelse(Temp == "amb", 0, Temp),
         Temp = as.numeric(Temp))
```

Initial plots

```{r}
ch4 %>%
  filter(CH4_rsquared > 0.9) %>%
  ggplot(aes(x = date, y = CH4_slope_ppm_per_day)) +
  geom_line(aes(group = plot_id))+
  facet_wrap(~zone_treatment)

ch4 %>%
  filter(CH4_rsquared > 0.9) %>%
  ggplot(aes(x = date, y = CH4_slope_ppm_per_day, color = zone_treatment)) +
  geom_smooth(se = F) +
  scale_color_viridis_d()
```

Something is interesting about how temperature treatments affect variability of methane fluxes

```{r}
all_dates <- ch4 %>%
  mutate(date_num = as.numeric(as.Date(flux_timestamp)),
         Year = year(flux_timestamp)) %>%
  group_by(plot_id, chamber_treatment, zone_treatment, Year) %>%
  expand(date_num = seq(min(date_num), max(date_num))) %>%
  mutate(Temp = sub("e", "", zone_treatment),
         Temp = ifelse(Temp == "amb", "0", Temp),
         Temp = as.numeric(Temp))

rolling <- ch4 %>% 
  filter(CH4_rsquared > 0.9) %>%
  mutate(date_num = as.numeric(as.Date(flux_timestamp))) %>%
  group_by(plot_id, chamber_treatment, zone_treatment) %>% #, date_num) %>%
  #summarize(CH4_slope_ppm_per_day = mean(CH4_slope_ppm_per_day, na.rm = T)) %>%
  full_join(all_dates) %>%
  arrange(date_num) %>%
  mutate(Rolling_sd = slider::slide_index_dbl(.x = CH4_slope_ppm_per_day, 
                                                  .i = date_num, 
                                                  .f = sd, 
                                                  na.rm = T,
                                                  .before = 30),
         Rolling_mean = slider::slide_index_dbl(.x = CH4_slope_ppm_per_day, 
                                                  .i = date_num, 
                                                  .f = mean, 
                                                  na.rm = T,
                                                  .before = 30),
         Temp_group = ifelse(Temp >= 3, "High", "Low")) 

rolling %>%
  pivot_longer(cols = c("Rolling_sd", "Rolling_mean"), names_to = "Variable", values_to = "Value") %>%
  ggplot(aes(x = as.Date(date_num), y = Value, color = zone_treatment, group = chamber_treatment)) +
  geom_line()+
  facet_grid(rows = vars(Temp_group), cols = vars(Variable)) +
  scale_color_viridis_d()

rolling %>%
  ggplot(aes(x = Rolling_mean, y = Rolling_sd, color = zone_treatment)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm") +
  scale_color_viridis_d()
```

What if we use medians instead?

```{r}
all_dates <- ch4 %>%
  mutate(date_num = as.numeric(as.Date(flux_timestamp)),
         Year = year(flux_timestamp)) %>%
  group_by(plot_id, chamber_treatment, zone_treatment, Year) %>%
  expand(date_num = seq(min(date_num), max(date_num))) %>%
  mutate(Temp = sub("e", "", zone_treatment),
         Temp = ifelse(Temp == "amb", "0", Temp),
         Temp = as.numeric(Temp))

rolling <- ch4 %>% 
  filter(CH4_rsquared > 0.9) %>%
  mutate(date_num = as.numeric(as.Date(flux_timestamp))) %>%
  group_by(plot_id, chamber_treatment, zone_treatment) %>% #, date_num) %>%
  #summarize(CH4_slope_ppm_per_day = mean(CH4_slope_ppm_per_day, na.rm = T)) %>%
  full_join(all_dates) %>%
  arrange(date_num) %>%
  mutate(Rolling_iqr = slider::slide_index_dbl(.x = CH4_slope_ppm_per_day, 
                                                  .i = date_num, 
                                                  .f = IQR, 
                                                  na.rm = T,
                                                  .before = 30),
         Rolling_median = slider::slide_index_dbl(.x = CH4_slope_ppm_per_day, 
                                                  .i = date_num, 
                                                  .f = median, 
                                                  na.rm = T,
                                                  .before = 30),
         Temp_group = ifelse(Temp >= 3, "High", "Low")) 

rolling %>%
  pivot_longer(cols = c("Rolling_iqr", "Rolling_median"), names_to = "Variable", values_to = "Value") %>%
  ggplot(aes(x = as.Date(date_num), y = Value, color = zone_treatment, group = chamber_treatment)) +
  geom_line()+
  facet_grid(rows = vars(Temp_group), cols = vars(Variable)) +
  scale_color_viridis_d()

rolling %>%
  ggplot(aes(x = Rolling_median, y = Rolling_iqr, color = zone_treatment)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm") +
  scale_color_viridis_d() 
```

Is this true within a day?

```{r}
daily <- ch4 %>% 
  filter(CH4_rsquared > 0.9) %>%
  mutate(date_num = as.numeric(as.Date(flux_timestamp))) %>%
  group_by(plot_id, chamber_treatment, zone_treatment, date_num) %>%
  mutate(Daily_sd = sd(CH4_slope_ppm_per_day, na.rm = T),
         Daily_mean = mean(CH4_slope_ppm_per_day, na.rm = T),
         Temp_group = ifelse(Temp >= 3, "High", "Low"),
         n = sum(!is.na(CH4_slope_ppm_per_day))) %>%
  filter(n > 5)

daily %>%
  pivot_longer(cols = c("Daily_sd", "Daily_mean"), names_to = "Variable", values_to = "Value") %>%
  ggplot(aes(x = as.Date(date_num), y = Value, color = zone_treatment, group = chamber_treatment)) +
  geom_line()+
  facet_grid(rows = vars(Temp_group), cols = vars(Variable)) +
  scale_color_viridis_d()

daily %>%
  ggplot(aes(x = Daily_mean, y = Daily_sd, color = zone_treatment)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm") +
  scale_color_viridis_d()

daily <- ch4 %>% 
  filter(CH4_rsquared > 0.9) %>%
  mutate(date_num = as.numeric(as.Date(flux_timestamp))) %>%
  group_by(plot_id, chamber_treatment, zone_treatment, date_num) %>%
  mutate(Daily_iqr = IQR(CH4_slope_ppm_per_day, na.rm = T),
         Daily_median = median(CH4_slope_ppm_per_day, na.rm = T),
         Temp_group = ifelse(Temp >= 3, "High", "Low"),
         n = sum(!is.na(CH4_slope_ppm_per_day))) %>%
  filter(n > 5)

daily %>%
  pivot_longer(cols = c("Daily_iqr", "Daily_median"), names_to = "Variable", values_to = "Value") %>%
  ggplot(aes(x = as.Date(date_num), y = Value, color = zone_treatment, group = chamber_treatment)) +
  geom_line()+
  facet_grid(rows = vars(Temp_group), cols = vars(Variable)) +
  scale_color_viridis_d()

daily %>%
  ggplot(aes(x = Daily_median, y = Daily_iqr, color = zone_treatment)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm") +
  scale_color_viridis_d()
```

Is this true within a day?

```{r}
ch4 %>% 
  filter(CH4_rsquared > 0.9) %>%
  mutate(date_num = as.numeric(as.Date(flux_timestamp)),
         hour = hour(flux_timestamp),
         year = year(flux_timestamp)) %>%
  ggplot(aes(x = hour, y = CH4_slope_umol_per_day, color = zone_treatment)) +
  geom_line(aes(group = date_num), alpha = 0.2)+
  facet_grid(rows = vars(zone_treatment), cols = vars(year)) +
  scale_color_viridis_d()+
  theme_bw()
```