install.packages("here")
install.packages("forecast")
install.packages("glmnet")
install.packages("prophet")
install.packages("randomForest")
install.packages("imputeTS")
install.packages("fabletools")
install.packages("fable")
install.packages("slider")
install.packages("rEDM")
sf <- "https://cran.r-project.org/src/contrib/Archive/sf/sf_0.9-0.tar.gz"
install.packages(sf, repos=NULL, type = "source")