---
title: "QAQC vis"
author: "Abby Lewis"
date: "2024-10-16"
output: html_document
---

Basically the same as the automated QAQC function, but with visualizations

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
#Remove really crazy values
slopes <- read_csv("../L0.csv", show_col_types = F) %>%
  filter(CH4_init < 4)

#Remove the worst 1% of fits
fit_cutoff <- quantile(slopes$CH4_rmse, 0.99)
#These poor fits have extreme values
slopes %>%
  ggplot(aes(x = CH4_init, y = CH4_slope_umol_per_day, color = CH4_rmse > fit_cutoff)) +
  geom_point() +
  geom_vline(xintercept = 1.5) +
  geom_vline(xintercept = 2.5) +
  scale_y_continuous(trans = scales::pseudo_log_trans(base = 10))

slopes_clean <- slopes %>%
  filter(CH4_rmse < fit_cutoff,
         CH4_init > 1.5,
         CH4_init < 2.5)

#R2 is not a good way to filter because this preferentially removes values near 0
slopes_clean %>%
  ggplot(aes(x = CH4_init, y = CH4_slope_umol_per_day, color = CH4_R2 > 0.7)) +
  geom_point()+
  scale_y_continuous(trans = scales::pseudo_log_trans(base = 10))

#High p-values are all close to 0 (good)
slopes_clean %>%
  ggplot(aes(x = CH4_init, y = CH4_slope_umol_per_day, color = CH4_p > 0.05)) +
  geom_point(alpha = 0.1) +
  scale_y_continuous(trans = scales::pseudo_log_trans(base = 10))

metadata <- read_csv("Raw_data/chamber_metadata.csv", show_col_types = F)
slopes_metadata <- metadata %>%
  left_join(slopes_clean %>%
              mutate(MIU_VALVE = as.numeric(MIU_VALVE)), 
            by = c("miu_valve" = "MIU_VALVE")) %>%
  rename(time2 = TIMESTAMP) %>%
  filter(year(time2) >= 2021)

write.csv(slopes_metadata, "L1.csv", row.names = FALSE)

slopes_clean %>%
  filter(year(TIMESTAMP) >= 2021) %>%
  ggplot(aes(x = TIMESTAMP, y = CH4_slope_umol_per_day)) +
  geom_point() +
  facet_wrap(~MIU_VALVE)

cleaned <- target %>%
  
  #No longer filtering by R2 (see download_data.R)
  
  #dplyr::mutate(
  #  #Generally trust negative fluxes less than daytime fluxes
  #  keep = ifelse(CH4_slope_umol_per_day < 0 & CH4_rsquared > 0.9, T, F),
  #  keep = ifelse(CH4_slope_umol_per_day > 0 & CH4_rsquared > 0.75, T, keep),
  #  #If CO2 is good, we should believe CH4
  #  keep = ifelse(CH4_slope_umol_per_day > 0 & CO2_rsquared > 0.9, T, keep)) %>%
  #dplyr::filter(keep) %>%
  dplyr::mutate(CH4_slope_umol_per_day = dplyr::if_else((time2 > as.Date("2023-03-02") & 
                                                           time2 < as.Date("2023-06-27")),
                                                        NA,
                                                        CH4_slope_umol_per_day)) #%>%
#dplyr::select(-keep)
```

## Plot all data

```{r}
slopes <- read_csv(here::here("L0.csv")) %>%
    dplyr::filter(TIMESTAMP <= as_datetime("2023-03-02") |
                    TIMESTAMP >= as_datetime("2023-06-27"))

plot_yearly_data <- function(year, slopes, gas) {
  p <- slopes %>%
    filter(year(TIMESTAMP) == year) %>%
    ggplot(aes(x = as.Date(TIMESTAMP), y = get(!!gas), color = hour(TIMESTAMP))) +
    geom_point(alpha = 0.2) +
    scale_color_gradientn(colors = c("blue", "red", "blue")) +
    facet_wrap(~MIU_VALVE) +
    ylab(gas)+
    scale_y_continuous(trans = "pseudo_log")+
    scale_x_date(date_labels = "%b")+
    theme(axis.title.x = element_blank())+
    ggtitle(year)
  print(p)
}

2021:2024 %>% 
  map(plot_yearly_data, slopes = slopes, gas = "CO2_slope_ppm_per_day")
2021:2024 %>% 
  map(plot_yearly_data, slopes = slopes, gas = "CH4_slope_ppm_per_day")
```

## 2024

Something is weird about the start of 2024, but I think what we are seeing is that data are /really good/.

In chambers 2:4, summer 2024 data is wrong

```{r}
plot_yearly_data(2024, slopes, gas = "CO2_slope_ppm_per_day")
plot_yearly_data(2024, slopes, gas = "CH4_slope_ppm_per_day")

plotly::ggplotly(
  slopes %>%
    filter(year(TIMESTAMP) == 2024) %>%
    mutate(hour = hour(TIMESTAMP)) %>%
    ggplot(aes(x = hour, y = CO2_slope_ppm_per_day, color = as.factor(month(TIMESTAMP)))) +
    facet_wrap(~MIU_VALVE)+
    #geom_point(alpha = 0.1)+
    geom_smooth(se = F)+
    scale_y_continuous(trans = "pseudo_log")
  )

slopes %>%
  filter(year(TIMESTAMP) == 2024,
         month(TIMESTAMP) >3) %>%
  mutate(hour = hour(TIMESTAMP)) %>%
  ggplot(aes(x = hour, y = CO2_slope_ppm_per_day, color = as.factor(month(TIMESTAMP)))) +
  facet_wrap(~MIU_VALVE)+
  #geom_point(alpha = 0.1)+
  geom_smooth(se = F)+
  guides(color = guide_legend(title = "Month"))+
  scale_y_continuous(trans = "pseudo_log")
```

```{r}
slopes %>%
  filter(year(TIMESTAMP) == 2021) %>%
  mutate(hour = hour(TIMESTAMP)) %>%
  ggplot(aes(x = hour, y = CO2_slope_ppm_per_day, color = as.factor(month(TIMESTAMP)))) +
  facet_wrap(~MIU_VALVE)+
  #geom_point(alpha = 0.1)+
  geom_smooth(se = F)+
  guides(color = guide_legend(title = "Month"))+
  scale_y_continuous(trans = "pseudo_log")
```
