---
title: "PEPRMT-Tidal JAGS"
output: html_document
date: "2024-11-15"
author: Abby Lewis
---

Load packages

```{r setup, echo=FALSE, message=FALSE}
library(pacman)
p_load(R.matlab, here, tidyverse, FME, Metrics, lubridate, gridExtra, rjags, coda)
source("run_PEPRMT.R")
source("PEPRMT_GPP_FINAL.R")
source("PEPRMT_CH4_FINAL_ASL2.R")
source("PEPRMT_Reco_FINAL.R")
```

Load data

```{r}
target <- read_csv("peprmt_target.csv") %>%
  as.data.frame() %>%
  mutate(NO3_mg_L = 0.062, #Copied from US_PLM
         WTD_cm = -WTD_cm) #Switch this when you update Load/Format data.Rmd

#First run GPP Module
GPP_theta <- c(0.7479271, 1.0497113, 149.4681710, 94.4532674 )
GPP_mod_target <- PEPRMT_GPP_final(GPP_theta,
                                   data = target)

#Create a new dataset that included model results
target_results <- target %>%
  left_join(GPP_mod_target %>%
              rename(GPP_mod = GPP,
                     DOY = Time_2),
            by = c("DOY", "site"))

#Second run Reco Module
#Add modeled GPP into data before running Reco module (16th column)
target[,16]<-target_results$GPP_mod

Reco_theta <- c(18.41329, 1487.65701, 11.65972, 61.29611 )
Reco_mod_target <- PEPRMT_Reco_FINAL(Reco_theta,
                                     data = target,
                                     wetland_type=2)

#Create a new dataset that included model results
target_results<-target_results %>%
  left_join(Reco_mod_target %>%
              rename(DOY = Time_2,
                     Reco_mod = Reco_full),
            by = c("DOY", "site"))

#Last, run CH4 module
#Add modeled S1, S2 into data before running CH4 module (17th & 18th columns)
target$SOM_total <- target_results$S1
target$SOM_labile <-target_results$S2

ch4_validation <- read_csv("ch4_validation.csv") %>%
  as.data.frame()

comb <- target %>%
  left_join(ch4_validation) %>%
  as.data.frame() %>%
  arrange(site, Date)
```

Temp + autoregressive term

```{r}
#Data
comb <- comb %>%
  arrange(site, DOY)
y <- comb$CH4_slope_umol_per_day
SOM_labile <- comb$SOM_labile
SOM_total <- comb$SOM_total

ind <- comb %>%
  mutate(ind = row_number()) %>%
  filter(!site==lag(site)) %>%
  pull(ind) %>%
  c(1, ., nrow(comb)+1)

model.inits <- list(tau_obs = 1,
                    tau_proc = 1)

#JAGS specifications
iterations <- 1000
burnin <- floor(iterations/2)
chains <- 3

model.fit <- jags.model(file="jags_model.txt",
                        data=list(y = y, 
                                  n_sites = length(unique(comb$site)),
                                  ind = ind,
                                  TA_C = comb$TA_C,
                                  WTD_cm = comb$WTD_cm,
                                  EVI = comb$EVI,
                                  LUE = comb$LUE,
                                  Salinity_daily_ave_ppt = comb$Salinity_daily_ave_ppt,
                                  NO3_mg_L = comb$NO3_mg_L,
                                  PAR_umol_m2_day = comb$PAR_umol_m2_day,
                                  SOM_labile = SOM_labile,
                                  SOM_total = SOM_total),
                        inits=model.inits, 
                        n.chains = chains)

model.samples <- coda.samples(
  model.fit, 
  c("tau_proc", "tau_obs"), 
  n.iter=iterations)
summary(window(model.samples, start = burnin))
plot(model.samples, trace=FALSE, density = TRUE)

output <- as.matrix(coda.samples(
  model.fit, c("mu"), 
  n.iter=iterations)) # extract the MCMC samples
pred <- colMeans(output) # point estimates and the variance
pred_interval <- apply(  # get 95% prediction intervals
  output, 2, 
  quantile, c(0.025, 0.975))

# arrange in a dataframe
df <- comb %>%
  mutate(pred = pred, 
         lpred = pred_interval[1,],
         upred = pred_interval[2,])


# plot the actual values, and predicted values and interval
ggplot(df, aes(x = Date)) + 
  geom_ribbon(aes(ymin = lpred, ymax = upred), alpha = 0.3, fill = "gray20") +
  geom_point(aes(y = CH4_slope_umol_per_day, col = "Observed"), size = 0.5) +
  geom_line(aes(y = pred, col = "Predicted"), linewidth = 0.5) +
  scale_color_manual(values = c("Observed" = "red", "Predicted" = "#4B0055"), name = "") +
  labs(y = "CH4_slope_umol_per_day", x = "Date") + 
  theme_minimal()+
  facet_wrap(~site)
```