---
title: "Process PAR"
author: "Abby Lewis"
date: "2024-09-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data_2021 <- read_csv("https://www.dropbox.com/scl/fi/qqgtyn9rbgw2qikcq940k/gcrewmet_gcrewmet15min_2021.csv?rlkey=lpbdtknt2zzhdxnm4q9sitnim&st=h4pxvo0w&dl=1")
data_2022 <- read_csv("https://www.dropbox.com/scl/fi/pi3fbv1zv9fi5mjn57foo/gcrewmet_gcrewmet15min_2022.csv?rlkey=57fu5pvwj66xgtecfyhwc7855&st=gzj56gcd&dl=1")
data_2023 <- read_csv("https://www.dropbox.com/scl/fi/kz083irzqpvny1b3azlcc/gcrewmet_gcrewmet15min_2023.csv?rlkey=8txix6edvh594zasxu9hnlw90&st=nv3q1gug&dl=1")
data_2024 <- read_csv("https://www.dropbox.com/scl/fi/ix9j9473mj4wbsw2odb50/gcrewmet_gcrewmet15min_2024.csv?rlkey=aa2xt1o7127kon0abwsxttl55&st=6dyxrczs&dl=1")

data_all <- bind_rows(data_2021, data_2022, data_2023, data_2024)

met_output <- data_all %>%
  mutate(time2 = with_tz(time2, tzone = "America/New_York"),
         Date = as.Date(time2)) %>%
  group_by(Date) %>%
  select(Date, par_den_c_avg, rain_cm_tot, barometric_pressure_pb110b, rh, ws_ms_rm_avg, slrw_avg) %>%
  mutate(rain_cm_tot = sum(rain_cm_tot, na.rm = TRUE)) %>% #Daily sums for rain
  summarize(across(is.numeric, mean, na.rm = TRUE))

data_all %>%
  ggplot(aes(x = par_den_c_avg, y = par_tot_c_tot)) +
  geom_point()

data_all %>%
  ggplot(aes(x = ws_ms_rm_avg, y = ws_ms_ws_avg)) +
  geom_point()

data_all %>%
  ggplot(aes(x = slrw_avg, y = par_den_c_avg, color = time2)) +
  geom_point()

write.csv(met_output %>% rename(PAR = par_den_c_avg) %>% select(Date, PAR), 
          "../processed_data/PAR_output.csv", row.names = FALSE)

write.csv(met_output,
          "../processed_data/met_output.csv", row.names = FALSE)
colnames(data_all)
```

