on:
  workflow_dispatch:
  schedule:
  - cron: "0 10 * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.2
    permissions:
      contents: write
      
    steps:
    - run: git config --system --add safe.directory '*'
    
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Run auto.arima
      run: |
        R -e 'utils::install.packages("here")'
        Rscript ./auto.arima/run_forecast.R
  
    - name: Run ETS
      run: |
        Rscript ./ETS/run_forecast.R

    - name: Run prophet
      run: |
        Rscript ./prophet/run_forecast.R
   
    - name: Run cwae
      run: |
        Rscript ./cwae/run_forecast.R
    
    - name: Commit and push
      run: |
        git config --global user.name 'abbylewis'
        git config --global user.email 'aslewis@vt.edu'
        git add .
        git commit -m "Automated time series forecasts" || echo "No changes to commit"
        git push
